### ISSUE TITLE
在文石 max lumi 上无法更新到1.0.2

### ISSUE THREAD

**Issue by bincat233** [zmk-ink/reabble-android#2]
1.0.0正常安装, 但是1.0.2会安装失败
设备为 boox max lumi, ARM64架构

**Comment by zmk-ink** [comment]
实在抱歉，是因为之前发布的1.0.0的安装文件是debug版本，因此导致1.0.2正式版无法覆盖安装。
请手动卸载已安装的1.0.0版本后，再安装1.0.2版（个别设备可能会需要重新登录reabble账号）

**Comment by bincat233** [comment]
感谢作者的回复!
不过卸载重装还是会安装失败

尝试使用adb安装, 报错:

```
Performing Streamed Install
adb: failed to install D:\Downloads\Reabble.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
```

搜索报错内容, 得到此[文章](https://www.jianshu.com/p/a02de0fbf229)

**Comment by bincat233** [comment]
@zmk-ink 或许需要重新打个包

**Comment by zmk-ink** [comment]
> @zmk-ink 或许需要重新打个包

那个包测过没问题的，我把 debug 版本的包也上传了，你试试看。

**Comment by zmk-ink** [comment]
> @zmk-ink 或许需要重新打个包

重新编译了，您再试试？

**Comment by bincat233** [comment]
@zmk-ink 好的，我一会儿试试去，谢谢你☺  (之前我是用 `adb install -t` 强制安装的)
