### ISSUE TITLE
返回键直接回到桌面

### ISSUE THREAD

**Issue by shinyypig** [zmk-ink/reabble-android#5]
好东西，刚买了5年。
我现在用的是墨案的mix7，这个墨水屏可以通过侧边划动实现返回键的功能。不过我发现，当进入文章页面后，我想返回到上一级目录，侧边划动直接退出程序回到桌面了。不知道作者能不能改一下对应的功能。

**Comment by zmk-ink** [comment]
按安卓系统返回键返回到文章列表功能，已经和 Reabble 作者碰过方案了，未来会做更新，日期暂没定下来，你可以先从中间向右滑动来返回上一级，并期待功能的更新：）

**Comment by shinyypig** [comment]
好的，辛苦辛苦！
