### ISSUE TITLE
Adopt for usage with Boox Go 10.3

### ISSUE THREAD

**Issue by tomillr** [zmk-ink/reabble-android#8]
Would it be possible to optimize the app for the new Boox Go 10.3 devices?

**Comment by zmk-ink** [comment]
The Boox Go 10.3 has the same screen size as the Tab 10, thus it's already supported. Where do you suggest we improve further?

**Comment by zmk-ink** [comment]
I apologize, even though the submitted code already supports Boox Tab10 and Boox Go 10.3 devices, the APK installation file hasn't been released yet. However, this version will be released soon.
