### ISSUE TITLE
Distribute through Google Play store

### ISSUE THREAD

**Issue by tomillr** [zmk-ink/reabble-android#9]
Any chance that you might make the app available through the Google Play store as well? The Boox devices have the official Google Play store already installed on their devices. Would be convenient, to be able to download and update the app right through the store without having to manually sideload it.

**Comment by zmk-ink** [comment]
This is a third-party app, not for profit. As a dedicated user, I cannot and do not intend to upload it to Google Play. Sorry for any inconvenience.
